### ISSUE TITLE
[enhancement] getPosts Api 개선 건의

### ISSUE THREAD

**Issue by ahnytae** [Frontend-ClassRoom/Movie-App-V1#10]
현재 getPosts api에서 offset/limit 옵션이 없어
프론트에서 100개를 한번에 가져오는데 위 옵션들 추가해서 잘라서 가져오는게
낫지않을까요?

**Comment by FRONT-JB** [comment]
getPosts 가 제가 임시로 달아놓은거라 다른 API에서 가져오고있어요( https://jsonplaceholder.typicode.com/ )
백엔드쪽 영향은 아니라서 추후에 본인 포스트를 가져오거나 다른 사람의 포스트를 가져올때 백엔드에서 가져오면 
경록선임님과 협의가 필요할것같아요
